build:
  image: python:2
  commands:
    - pip install -r requirements.txt
    - flake8
    - nosetests -v
  environment:
    - PIP_DOWNLOAD_CACHE=/drone/pip_download_cache
cache:
  mount:
    - /drone/pip_download_cache
