---
- hosts: all

  vars:
    home_dir: /home/vagrant
    xsupplicant_src: "{{ home_dir }}/xsupplicant"
    xsupplicant_repo: https://titan.ais.cmc.osaka-u.ac.jp/core-grid/xsupplicant.git
    direnv_url: https://github.com/zimbatm/direnv/releases/download/v2.6.0/direnv.linux-amd64
    direnv_sha: 8b9fc5362e8f4d338f73fe022026423ffbf72c316a6ef8447629e08a1488422d
    mnexec_url: https://raw.githubusercontent.com/mininet/mininet/96ea5367dbea7b77e6b7454c1de85b30b7ba7035/mnexec.c
    mnexec_sha: 4377b573054f75707f37d8c2b8d7d8a7f12647e7b6eeaaeca529129001606251
    direnv_allow_hash: 5945516c60bc0e77173b9dd717a8c6cbc31dc98d0b6a087e35a640e6b73da9e9
    direnv_allow_file: "{{ home_dir }}/.config/direnv/allow/{{ direnv_allow_hash }}"

  tasks:

    - name: Install required apt packages
      apt: name={{ item }} state=latest
      with_items:
        - language-pack-ja
        - mininet
        - python-pip
        - python2.7-dev
    - name: Download mnexec
      get_url: url={{ mnexec_url }}
               sha256sum={{ mnexec_sha }}
               dest={{ home_dir }}/mnexec.c
      become: no
    - name: Build mnexec
      command: gcc -O3 -Wall -Wextra -o mnexec mnexec.c
        chdir={{ home_dir }}
        creates=mnexec
      become: no
    - name: Install mnexec
      command: install -o root -g root -m 0755 mnexec /usr/local/bin/mnexec
        chdir={{ home_dir }}
        creates=/usr/local/bin/mnexec

    - name: Download direnv
      get_url: url={{ direnv_url }}
               sha256sum={{ direnv_sha }}
               dest=/usr/local/bin/direnv
               owner=root
               group=root
               mode=0755
    - name: Install direnv profile hook
      copy: content='eval "$(direnv hook bash)"'
            dest=/etc/profile.d/direnv.sh
            owner=root
            group=root
            mode=0644
    - name: Install virtualenv
      pip: name=virtualenv
    - name: Execute direnv allow on project directory
      shell: direnv allow chdir=/vagrant creates={{ direnv_allow_file }}
      become: no
    - name: Install pip dependencies
      pip: chdir=/vagrant requirements=/vagrant/requirements.txt state=latest
      become: no

    - name: Install apt packages for xsupplicant
      apt: name={{ item }} state=latest
      with_items:
        - git
        - autoconf
        - automake
        - libtool
        - pkg-config
        - libxml2-dev
        - libssl-dev
        - libiw-dev
    - name: Prevent git hangs
      copy: content='Host *\nServerAliveInterval 60\n'
            dest={{ home_dir }}/.ssh/config
      become: no
    - name: Set git postBuffer
      copy: content='[http]\npostBuffer = 2M\n'
            dest={{ home_dir }}/.gitconfig
      become: no
    - name: Clone xsupplicant source code
      git: repo=https://titan.ais.cmc.osaka-u.ac.jp/core-grid/xsupplicant.git
           dest={{ xsupplicant_src }} depth=1 accept_hostkey=yes
      become: no
    - name: Generate configure file for xsupplicant
      command: ./autoregen.sh
        chdir={{ xsupplicant_src }}/xsupplicant
        creates=configure
      become: no
    - name: Configure xsupplicant
      shell: LIBS="-lz -ldl" ./configure
        chdir={{ xsupplicant_src }}/xsupplicant
        creates=Makefile
      become: no
    - name: Make xsupplicant
      command: make
        chdir={{ xsupplicant_src }}/xsupplicant
        creates=src/xsupplicant
      become: no
    - name: Make install xsupplicant
      command: make install
        chdir={{ xsupplicant_src }}/xsupplicant
        creates=/usr/local/sbin/xsupplicant
